"""
nusmv_model.py — Stage 5a: Generate the NuSMV protocol model (.smv).

Key improvements over v1:
  1. Actor-local control states (EVCC and SECC substates)
  2. Shared message channel with constrained variable domains
  3. Timers as bounded counters (not free nondeterminism)
  4. Retry counters bounded per spec
  5. ISO variable names preserved
  6. Guard conditions derived from requirement atoms (not placeholders)
  7. Turn-based execution (EVCC turn, SECC turn)
"""

from __future__ import annotations

import re
from io import StringIO
from typing import Optional

from models import (
    Atom, AtomKind, AtomScope, GuardStatus, NuSMVVar,
    ProtocolModel, ProtocolState, ProtocolTransition, Role,
)
from config import PipelineConfig


# ═══════════════════════════════════════════════════════════════════════════
# SMV name sanitizer
# ═══════════════════════════════════════════════════════════════════════════

_SMV_RESERVED = {
    "MODULE", "VAR", "IVAR", "DEFINE", "ASSIGN", "INIT", "TRANS", "INVAR",
    "SPEC", "CTLSPEC", "LTLSPEC", "FAIRNESS", "JUSTICE", "COMPASSION",
    "TRUE", "FALSE", "case", "esac", "next", "init", "self", "process",
    "mod", "union", "in", "xor", "xnor",
}


def smv_name(iso_name: str) -> str:
    """Sanitize an ISO variable name for NuSMV. Preserve name where possible."""
    name = re.sub(r'[^a-zA-Z0-9_]', '_', iso_name)
    if name.upper() in _SMV_RESERVED or name[0:1].isdigit():
        name = "v_" + name
    return name


def smv_enum_val(val: str) -> str:
    """Sanitize an enumeration value for NuSMV."""
    val = re.sub(r'[^a-zA-Z0-9_]', '_', val)
    if val.upper() in _SMV_RESERVED or val[0:1].isdigit():
        val = "e_" + val
    return val


# ═══════════════════════════════════════════════════════════════════════════
# NuSMV code emitter
# ═══════════════════════════════════════════════════════════════════════════

class NuSMVEmitter:
    """Generates NuSMV .smv code from a ProtocolModel."""

    def __init__(self, model: ProtocolModel, config: PipelineConfig):
        self.model = model
        self.config = config
        self.buf = StringIO()
        self._indent = 0

        # Precompute mappings
        self.state_names = [s.name for s in model.states]
        self.state_smv = {s.name: smv_name(s.name) for s in model.states}

    def emit(self) -> str:
        """Generate the full SMV model."""
        self._header()
        self._module_main()
        return self.buf.getvalue()

    # ── Header ─────────────────────────────────────────────────────────

    def _header(self):
        self._line(f"-- {self.model.title}")
        self._line(f"-- Generated by AC Protocol Model Checker v2")
        self._line(f"-- States: {len(self.model.states)}, "
                   f"Transitions: {len(self.model.transitions)}, "
                   f"Variables: {len(self.model.variables)}")
        self._line()

    # ── Main module ────────────────────────────────────────────────────

    def _module_main(self):
        self._line("MODULE main")
        self._line()
        self._section_var()
        self._section_assign()
        self._section_trans()
        if self.config.include_timing:
            self._section_timers()
        self._section_invar()
        self._section_fairness()

    # ── VAR section ────────────────────────────────────────────────────

    def _section_var(self):
        self._line("VAR")
        self._indent += 1

        # Turn variable
        self._line("-- Turn-based execution")
        self._line("turn : {evcc_turn, secc_turn};")
        self._line()

        # Protocol state
        self._line("-- Protocol state (shared)")
        state_vals = ", ".join(self.state_smv[s] for s in self.state_names)
        self._line(f"proto_state : {{{state_vals}}};")
        self._line()

        # Actor-local control states
        if self.config.include_actor_local and self.model.evcc_local:
            self._line("-- EVCC control state")
            evcc_vals = ", ".join(smv_name(s) for s in self.model.evcc_local.control_states[:30])
            if len(self.model.evcc_local.control_states) > 30:
                evcc_vals += ", EVCC_Other"
            self._line(f"evcc_ctrl : {{{evcc_vals}}};")
            self._line()

        if self.config.include_actor_local and self.model.secc_local:
            self._line("-- SECC control state")
            secc_vals = ", ".join(smv_name(s) for s in self.model.secc_local.control_states[:30])
            if len(self.model.secc_local.control_states) > 30:
                secc_vals += ", SECC_Other"
            self._line(f"secc_ctrl : {{{secc_vals}}};")
            self._line()

        # Message channel
        self._line("-- Message channel")
        msg_types = ["none"]
        for s in self.model.states:
            if s.allowed_request:
                msg_types.append(smv_name(s.allowed_request))
            if s.allowed_response:
                msg_types.append(smv_name(s.allowed_response))
        msg_vals = ", ".join(dict.fromkeys(msg_types))  # deduplicate
        self._line(f"msg_channel : {{{msg_vals}}};")
        self._line()

        # Protocol variables (ISO names)
        self._line("-- Protocol variables (ISO names preserved)")
        for var in self.model.variables:
            if var.domain == ["boolean"]:
                self._line(f"{smv_name(var.iso_name)} : boolean;"
                           f"  -- {var.description}")
            else:
                vals = ", ".join(smv_enum_val(v) for v in var.domain)
                self._line(f"{smv_name(var.iso_name)} : {{{vals}}};"
                           f"  -- {var.description}")
        self._line()

        # Retry counter
        if self.config.include_retries:
            self._line("-- Retry counter")
            self._line(f"retry_count : 0..{self.config.max_retry_count};")
            self._line()

        # Timer abstraction
        if self.config.include_timing and self.model.timers:
            self._line("-- Timer (abstracted)")
            self._line(f"timer_tick : 0..{self.config.timer_abstraction};")
            self._line(f"timer_expired : boolean;")
            self._line()

        self._indent -= 1

    # ── ASSIGN section ─────────────────────────────────────────────────

    def _section_assign(self):
        self._line("ASSIGN")
        self._indent += 1

        # init(turn)
        self._line("init(turn) := evcc_turn;")

        # init(proto_state)
        entry = self.state_smv.get(self.model.entry_state, self.state_smv.get(self.state_names[0]))
        self._line(f"init(proto_state) := {entry};")

        # init(msg_channel)
        self._line("init(msg_channel) := none;")

        # init protocol variables
        for var in self.model.variables:
            if var.domain == ["boolean"]:
                self._line(f"init({smv_name(var.iso_name)}) := {var.init_value};")
            else:
                self._line(f"init({smv_name(var.iso_name)}) := {smv_enum_val(var.init_value)};")

        if self.config.include_retries:
            self._line("init(retry_count) := 0;")

        if self.config.include_timing and self.model.timers:
            self._line("init(timer_tick) := 0;")
            self._line("init(timer_expired) := FALSE;")

        # Actor-local inits
        if self.config.include_actor_local and self.model.evcc_local:
            self._line(f"init(evcc_ctrl) := {smv_name(self.model.evcc_local.init_state)};")
        if self.config.include_actor_local and self.model.secc_local:
            self._line(f"init(secc_ctrl) := {smv_name(self.model.secc_local.init_state)};")

        self._line()

        # ── next(turn) — alternating ──
        self._line("-- Turn alternation")
        self._line("next(turn) := case")
        self._indent += 1
        self._line("turn = evcc_turn : secc_turn;")
        self._line("turn = secc_turn : evcc_turn;")
        self._line("TRUE : turn;")
        self._indent -= 1
        self._line("esac;")
        self._line()

        # ── next(proto_state) — the main FSM ──
        self._line("-- Protocol state transitions")
        self._line("next(proto_state) := case")
        self._indent += 1
        self._emit_state_transitions()
        self._line("TRUE : proto_state;")
        self._indent -= 1
        self._line("esac;")
        self._line()

        # ── next(msg_channel) ──
        self._emit_msg_channel_next()

        # ── next for protocol variables ──
        self._emit_variable_nexts()

        # ── next for retry counter ──
        if self.config.include_retries:
            self._emit_retry_next()

        # ── next for timer ──
        if self.config.include_timing and self.model.timers:
            self._emit_timer_next()

        self._indent -= 1
        self._line()

    def _emit_state_transitions(self):
        """Emit case branches for proto_state transitions.

        For states with multiple outgoing transitions where some have guards
        and some don't, the guardless transitions get explicit negation of
        all sibling guards (no unconstrained TRUE fallthrough).
        """
        # Group transitions by from_state
        by_state: dict[str, list[ProtocolTransition]] = {}
        for t in self.model.transitions:
            by_state.setdefault(t.from_state, []).append(t)

        for state_name in self.state_names:
            trans_list = by_state.get(state_name, [])
            if not trans_list:
                continue

            from_smv = self.state_smv[state_name]

            # Identify guarded vs unguarded transitions
            guarded = [(t, self._build_guard_expr(t)) for t in trans_list]
            has_guards = [g for g in guarded if g[1]]
            no_guards = [g for g in guarded if not g[1]]

            for t, guard_expr in has_guards:
                to_smv = self.state_smv[t.to_state]
                self._line(f"-- T{t.id}: {t.from_state} -> {t.to_state}")
                self._line(f"proto_state = {from_smv} & {guard_expr} : {to_smv};")

            # For unguarded transitions in a multi-exit state,
            # use negation of all sibling guards (not bare TRUE)
            if no_guards and has_guards:
                sibling_guards = [g for _, g in has_guards if g]
                negation = " & ".join(f"!({g})" for g in sibling_guards)
                for t, _ in no_guards:
                    to_smv = self.state_smv[t.to_state]
                    self._line(f"-- T{t.id}: {t.from_state} -> {t.to_state} (else branch)")
                    self._line(f"proto_state = {from_smv} & {negation} : {to_smv};")
            elif no_guards and not has_guards:
                # All unguarded — emit as-is (single exit or all ambiguous)
                for t, _ in no_guards:
                    to_smv = self.state_smv[t.to_state]
                    self._line(f"-- T{t.id}: {t.from_state} -> {t.to_state}")
                    self._line(f"proto_state = {from_smv} : {to_smv};")

    def _build_guard_expr(self, trans: ProtocolTransition) -> str:
        """
        Build a NuSMV guard expression from a transition's guard atoms.

        When the same variable appears with multiple different values
        (from different requirement atoms), these are merged into a
        disjunction (OR), since they represent alternative conditions
        from different spec requirements, not a simultaneous conjunction.

        Undeclared variables (not in model.variables) are filtered out.
        """
        # First, collect all var=val pairs, grouped by variable
        var_vals: dict[str, list[str]] = {}  # var_smv → [val_smv, ...]
        non_var_parts: list[str] = []
        declared_vars = {v.iso_name for v in self.model.variables}

        for guard in trans.guards:
            smv_expr = self._atom_to_smv(guard)
            if not smv_expr:
                continue

            # Parse var = val pattern
            m = re.match(r'(\w+)\s*=\s*(\w+)', guard.expr)
            if m:
                var_name = m.group(1)
                # Filter out undeclared variables
                if var_name not in declared_vars:
                    continue
                svar = smv_name(var_name)
                val = m.group(2)
                sval = val.upper() if val.upper() in ("TRUE", "FALSE") else smv_enum_val(val)
                var_vals.setdefault(svar, []).append(sval)
            else:
                non_var_parts.append(smv_expr)

        # Build parts: single-value → equality, multi-value → disjunction
        parts = []
        for svar, vals in var_vals.items():
            unique_vals = list(dict.fromkeys(vals))  # deduplicate, preserve order
            if len(unique_vals) == 1:
                parts.append(f"{svar} = {unique_vals[0]}")
            else:
                disj = " | ".join(f"{svar} = {v}" for v in unique_vals)
                parts.append(f"({disj})")

        parts.extend(non_var_parts)

        # For turn-gated transitions, add turn constraint
        if trans.evcc_refs and not trans.secc_refs:
            parts.append("turn = evcc_turn")
        elif trans.secc_refs and not trans.evcc_refs:
            parts.append("turn = secc_turn")

        if not parts:
            return ""

        return " & ".join(f"({p})" for p in parts)

    def _atom_to_smv(self, atom: Atom) -> str:
        """Convert an atom expression to NuSMV syntax."""
        expr = atom.expr

        # Pattern: VarName = Value
        m = re.match(r'(\w+)\s*=\s*(\w+)', expr)
        if m:
            var, val = m.group(1), m.group(2)
            svar = smv_name(var)
            # Check if it's a boolean
            if val.upper() in ("TRUE", "FALSE"):
                return f"{svar} = {val.upper()}"
            else:
                return f"{svar} = {smv_enum_val(val)}"

        # Pattern: send(Message) / respond(Message)
        m = re.match(r'(?:send|respond)\((\w+)\)', expr)
        if m:
            msg = m.group(1)
            return f"msg_channel = {smv_name(msg)}"

        # Pattern: timer(TimerName) — timeout check
        m = re.match(r'timer\((\w+)\)', expr)
        if m:
            return "timer_expired = TRUE"

        # Fallback: try direct use
        return ""

    def _emit_msg_channel_next(self):
        """Generate next(msg_channel) based on state transitions."""
        self._line("-- Message channel follows protocol state")
        self._line("next(msg_channel) := case")
        self._indent += 1

        for state in self.model.states:
            ss = self.state_smv[state.name]
            if state.allowed_request:
                self._line(f"next(proto_state) = {ss} & turn = evcc_turn : "
                           f"{smv_name(state.allowed_request)};")
            if state.allowed_response:
                self._line(f"next(proto_state) = {ss} & turn = secc_turn : "
                           f"{smv_name(state.allowed_response)};")

        self._line("TRUE : none;")
        self._indent -= 1
        self._line("esac;")
        self._line()

    def _emit_variable_nexts(self):
        """
        Generate next() for protocol variables.

        Key improvement: uses per-state variable constraints from enrichment
        to restrict nondeterminism. Instead of allowing ALL domain values
        everywhere, each state only allows values that appear in guard
        conditions for outgoing transitions from that state.
        """
        state_constraints = getattr(self.model, 'state_variable_constraints', {})

        for var in self.model.variables:
            sname = smv_name(var.iso_name)

            # Collect all action atoms that set this variable
            setters: list[tuple[str, str, str]] = []  # (state_guard, value, comment)
            for t in self.model.transitions:
                for atom in t.actions + t.field_constraints:
                    m = re.match(r'(?:send|respond)\((\w+)\)', atom.expr)
                    if m:
                        continue  # skip message sends
                    m = re.match(rf'{re.escape(var.iso_name)}\s*=\s*(\w+)', atom.expr)
                    if m:
                        val = m.group(1)
                        from_smv = self.state_smv[t.from_state]
                        guard = f"proto_state = {from_smv}"
                        setters.append((guard, val, f"T{t.id}"))

            if not setters:
                # No action sets this variable → constrained nondeterminism per state
                if var.domain == ["boolean"]:
                    self._line(f"-- {sname}: constrained nondeterministic (boolean)")
                    self._line(f"next({sname}) := {{{sname}, !{sname}}};")
                else:
                    # Build per-state constrained domain
                    has_state_constraints = False
                    state_branches = []

                    for state_name in self.state_names:
                        key = (state_name, var.iso_name)
                        if key in state_constraints:
                            allowed = state_constraints[key]
                            if allowed:
                                from_smv = self.state_smv[state_name]
                                vals = ", ".join(
                                    smv_enum_val(v) for v in sorted(allowed)
                                    if v in var.domain or v.upper() in ("TRUE", "FALSE")
                                )
                                if vals:
                                    state_branches.append(
                                        (from_smv, vals, state_name)
                                    )
                                    has_state_constraints = True

                    if has_state_constraints:
                        self._line(f"-- {sname}: per-state constrained")
                        self._line(f"next({sname}) := case")
                        self._indent += 1
                        for from_smv, vals, sn in state_branches:
                            self._line(f"proto_state = {from_smv} : {{{vals}}};  -- at {sn}")
                        # Default: keep current value (no free nondeterminism)
                        self._line(f"TRUE : {sname};")
                        self._indent -= 1
                        self._line("esac;")
                    else:
                        # No constraints found — keep current value
                        self._line(f"-- {sname}: no state constraints, keep value")
                        self._line(f"next({sname}) := {sname};")
            else:
                self._line(f"-- {sname}: updated by actions")
                self._line(f"next({sname}) := case")
                self._indent += 1
                for guard, val, comment in setters:
                    if val.upper() in ("TRUE", "FALSE"):
                        self._line(f"{guard} : {val.upper()};  -- {comment}")
                    else:
                        self._line(f"{guard} : {smv_enum_val(val)};  -- {comment}")
                self._line(f"TRUE : {sname};")
                self._indent -= 1
                self._line("esac;")
            self._line()

    def _emit_retry_next(self):
        """Generate next(retry_count)."""
        self._line("-- Retry counter")
        self._line("next(retry_count) := case")
        self._indent += 1

        # Reset on state change
        self._line("next(proto_state) != proto_state : 0;")
        # Increment on self-loop
        self._line(f"next(proto_state) = proto_state & "
                   f"retry_count < {self.config.max_retry_count} : "
                   f"retry_count + 1;")
        self._line("TRUE : retry_count;")

        self._indent -= 1
        self._line("esac;")
        self._line()

    def _emit_timer_next(self):
        """Generate timer abstraction."""
        self._line("-- Timer abstraction")
        self._line("next(timer_tick) := case")
        self._indent += 1
        self._line("next(proto_state) != proto_state : 0;  -- reset on state change")
        self._line(f"timer_tick < {self.config.timer_abstraction} : timer_tick + 1;")
        self._line("TRUE : timer_tick;")
        self._indent -= 1
        self._line("esac;")
        self._line()
        self._line(f"next(timer_expired) := timer_tick >= {self.config.timer_abstraction};")
        self._line()

    # ── TRANS section ──────────────────────────────────────────────────

    def _section_trans(self):
        """Generate explicit TRANS constraints for mutual exclusion of transitions."""
        # For states with multiple outgoing transitions, ensure mutual exclusion
        self._line("-- Transition mutual exclusion constraints")

        by_state: dict[str, list[ProtocolTransition]] = {}
        for t in self.model.transitions:
            by_state.setdefault(t.from_state, []).append(t)

        for state_name, trans_list in by_state.items():
            if len(trans_list) <= 1:
                continue

            # Only emit TRANS if multiple transitions have guards
            guarded = [t for t in trans_list if t.guards]
            if len(guarded) < 2:
                continue

            from_smv = self.state_smv[state_name]
            self._line(f"-- Mutual exclusion for transitions from {state_name}")

            # Generate pairwise exclusion for transitions with incompatible guards
            for i, t1 in enumerate(guarded):
                for t2 in guarded[i + 1:]:
                    g1 = self._build_guard_expr(t1)
                    g2 = self._build_guard_expr(t2)
                    if g1 and g2:
                        self._line(f"TRANS proto_state = {from_smv} -> "
                                   f"!({g1} & {g2})")

        self._line()

    # ── INVAR section ──────────────────────────────────────────────────

    def _section_invar(self):
        """Generate INVAR constraints from invariant atoms."""
        invariants = []

        # State-level invariants
        for state in self.model.states:
            for atom in state.invariants:
                smv_expr = self._atom_to_smv(atom)
                if smv_expr:
                    from_smv = self.state_smv[state.name]
                    invariants.append(
                        (f"proto_state = {from_smv} -> {smv_expr}",
                         atom.source_req)
                    )

        # Global invariants
        for atom in self.model.global_atoms:
            if atom.kind == AtomKind.INVARIANT:
                smv_expr = self._atom_to_smv(atom)
                if smv_expr:
                    invariants.append((smv_expr, atom.source_req))

        if invariants:
            self._line("-- Invariants from requirements")
            for expr, req_id in invariants:
                self._line(f"INVAR {expr}  -- {req_id}")
            self._line()

    # ── FAIRNESS section ───────────────────────────────────────────────

    def _section_fairness(self):
        """Generate fairness constraints."""
        self._line("-- Fairness: both actors get infinite turns")
        self._line("FAIRNESS turn = evcc_turn")
        self._line("FAIRNESS turn = secc_turn")
        self._line()

        # State fairness: eventually leave each non-terminal state
        exit_smv = self.state_smv.get(self.model.exit_state, "")
        for state in self.model.states:
            s = self.state_smv[state.name]
            if s != exit_smv:
                self._line(f"FAIRNESS !(proto_state = {s})")
        self._line()

    # ── Timer section ──────────────────────────────────────────────────

    def _section_timers(self):
        """Generate timer-related comments and constraints."""
        if not self.model.timers:
            return

        self._line("-- Timer specifications (from Table 215)")
        for timer in self.model.timers:
            self._line(f"-- {timer.name}: {timer.value_seconds}s "
                       f"({timer.applicable_to.value})"
                       f"{' for ' + timer.message_type if timer.message_type else ''}")
        self._line()

    # ── Helpers ────────────────────────────────────────────────────────

    def _line(self, text: str = ""):
        indent = "  " * self._indent
        self.buf.write(f"{indent}{text}\n")


# ═══════════════════════════════════════════════════════════════════════════
# Main entry point
# ═══════════════════════════════════════════════════════════════════════════

def generate_smv_model(
    model: ProtocolModel,
    config: PipelineConfig,
) -> str:
    """Generate the NuSMV protocol model as a string."""
    emitter = NuSMVEmitter(model, config)
    return emitter.emit()
